"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Banco_1 = require("./modules/Banco");
var c1 = new Banco_1.Conta('123', 1000);
var c2 = new Banco_1.Conta('321', 200);
var c3 = new Banco_1.Conta('456', 600);
c1.depositar(100);
console.log(c1.saldo);
c1.sacar(200);
console.log(c1.saldo);
c1.transferir(c2, 300);
console.log(c1.saldo);
console.log(c2.saldo);
var banco = new Banco_1.Banco([c1, c2, c3]);
console.log(banco.contas);
console.log(banco.consultar('123'));
banco.alterar(c2);
banco.excluir('123');
console.log(banco.contas);
banco.depositar('456', 300);
console.log(c3.saldo);
